import type { Metadata } from "next";

import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { authOptions } from "@/utils/authOptions";
import { getServerSession } from "next-auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Simply Good Food",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedUser = await getServerSession(authOptions);

  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar loggedUser={loggedUser} />
        <div className="min-h-screen w-[90%] mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
